production:
  services:
    fluent:
      image: khash/simple_web
      command: some command
      ports: ['3000:80:443']
      log_folder: /var/deploy/app/app.log
    databases:
      - 'postgresql'