production:
  services:
    web: 
      image: quay.io/cloud66/sample-rails
      command: rackup -p 3000
      build_command: rake db:migrate
      deploy_command: rake db:migrate
      ports: ["3000:80:443"]
      volumes: ["/tmp:/tmp_host:ro"]
      log_folder: /usr/src/app/log
      requires: ["rethinkdb"]
    rethinkdb:
      image: barkerja/rethinkdb
      command: rethinkdb --bind all
      ports: ["8080:8080"]
      log_folder: /var/deploy/rethinkdb/log
  databases:
    - "mysql"
